name: CI Pipeline

on:
  push:
    branches: [ main, reg, hyper ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run regression analysis
      run: |
        python regression.py
    
    - name: Run hyperparameter tuning
      if: github.ref == 'refs/heads/hyper' || github.ref == 'refs/heads/main'
      run: |
        python hyperparameter_tuning.py
    
    - name: Upload regression results
      uses: actions/upload-artifact@v3
      with:
        name: regression-results
        path: regression_results.json
    
    - name: Upload hyperparameter results
      if: github.ref == 'refs/heads/hyper' || github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v3
      with:
        name: hyperparameter-results
        path: hyperparameter_results.json
